# Generated by Django 2.2.4 on 2019-08-29 03:54

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDb',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name_english', models.CharField(max_length=50, unique=True)),
                ('name_japanese', models.CharField(max_length=50)),
                ('type', models.PositiveIntegerField()),
                ('price_buy', models.PositiveIntegerField(blank=True, null=True)),
                ('price_sell', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.PositiveSmallIntegerField()),
                ('attack', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('defence', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('range', models.PositiveIntegerField(blank=True, null=True)),
                ('slots', models.PositiveIntegerField(blank=True, null=True)),
                ('equip_jobs', models.BigIntegerField(blank=True, null=True)),
                ('equip_upper', models.PositiveIntegerField(blank=True, null=True)),
                ('equip_genders', models.PositiveIntegerField(blank=True, null=True)),
                ('equip_locations', models.PositiveIntegerField(blank=True, null=True)),
                ('weapon_level', models.PositiveIntegerField(blank=True, null=True)),
                ('equip_level', models.PositiveIntegerField(blank=True, null=True)),
                ('refineable', models.PositiveIntegerField(blank=True, null=True)),
                ('view', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('script', models.TextField(blank=True, null=True)),
                ('equip_script', models.TextField(blank=True, null=True)),
                ('unequip_script', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item_db',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.CharField(max_length=255)),
                ('user_pass', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=255)),
                ('group_id', models.IntegerField(default=0)),
                ('state', models.PositiveIntegerField(default=0)),
                ('unban_time', models.PositiveIntegerField(default=0)),
                ('expiration_time', models.PositiveIntegerField(default=0)),
                ('logincount', models.PositiveIntegerField(default=0)),
                ('lastlogin', models.DateTimeField(blank=True, null=True)),
                ('last_ip', models.CharField(max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('character_slots', models.PositiveIntegerField(default=15)),
                ('pincode', models.CharField(blank=True, max_length=4)),
                ('pincode_change', models.PositiveIntegerField(default=0)),
                ('vip_time', models.PositiveIntegerField(default=0)),
                ('old_group', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('badges', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('img_url', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('create_at', models.DateTimeField(default=datetime.datetime(2019, 8, 29, 3, 54, 47, 954324, tzinfo=utc))),
                ('expired_at', models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 29, 4, 9, 47, 954347, tzinfo=utc), null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Login')),
            ],
        ),
    ]
