# Generated by Django 2.2.4 on 2019-08-30 06:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 30, 6, 54, 6, 279630, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 30, 7, 9, 6, 279654, tzinfo=utc), null=True),
        ),
    ]
