# Generated by Django 2.2.4 on 2019-08-31 10:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190830_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 31, 10, 9, 32, 53778, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 8, 31, 10, 24, 32, 53810, tzinfo=utc), null=True),
        ),
    ]
