# Generated by Django 2.2.4 on 2019-09-01 09:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190901_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='is_carousel',
            new_name='show_on_carousel',
        ),
        migrations.AlterField(
            model_name='token',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 9, 8, 48, 857954, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='expired_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 9, 1, 9, 23, 48, 857978, tzinfo=utc), null=True),
        ),
    ]
